services:
  ionic-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8101:8100"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npx ionic serve --host=0.0.0.0